trigger:
- main

pool:
  name: onpremisepool

steps:

- checkout: self

- script: mvn clean package
  displayName: 'Build WAR with Maven'

- script: docker build -t cicd-webapp:latest .
  displayName: 'Build Docker image'

- powershell: |
    Write-Host "Removing old container if it exists..."

    docker rm -f cicd-webapp 2>$null

    Write-Host "Starting new container..."

    docker run -d `
      --name cicd-webapp `
      -p 8080:8080 `
      cicd-webapp:latest

    Write-Host "Running containers:"

    docker ps
  displayName: 'Deploy Docker container'